---
driver:
  name: vagrant
  chef_version: current

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"

verifier:
  name: inspec

verifier:
  name: inspec

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
- name: debian-7.11
- name: debian-8.7
- name: centos-6.9
- name: centos-7.3
- name: fedora-25
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: freebsd-11.0
- name: opensuse-leap-42.2

suites:
- name: default
  run_list:
    - recipe[sysctl_test::default]
    - recipe[sysctl::ohai_plugin]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
- name: lwrps
  run_list:
    - recipe[sysctl_test]
- name: attributes
  run_list:
    - recipe[sysctl::apply]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        dev:
          cdrom:
            autoeject: 1
