---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"
  roles_path: "roles"
  environments_path: "environments"
  require_chef_omnibus: true

verifier:
  name: inspec

client_rb:
  treat_deprecation_warnings_as_errors: true
  resource_cloning: false

platforms:
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: debian-7.11
- name: debian-8.7
- name: centos-6.8
- name: centos-7.3
- name: fedora-25
- name: freebsd-11
- name: scientific-6.4
  driver:
    box: lyte-scientific-6-minimal
    box_url: http://lyte.id.au/vagrant/sl6-64-lyte.box
- name: arch
  driver:
    box: srijn-arch-2014-01-07
    box_url:  http://vagrant.srijn.net/archlinux-x64-2014-01-07.box

suites:
- name: default
  run_list:
    - recipe[sysctl_test::default]
    - recipe[sysctl_test::tcp_wmem]
    - recipe[sysctl::ohai_plugin]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
- name: lwrps
  run_list:
    - recipe[sysctl_test]
    - recipe[sysctl_test::tcp_wmem]
- name: attributes
  run_list:
    - recipe[sysctl::apply]
  attributes:
    sysctl:
      params:
        vm:
          swappiness: 19
        net:
          ipv4:
            tcp_fin_timeout: 29
