---
driver:
  name: vagrant
  chef_version: current

provisioner:
  name: chef_zero
  data_bags_path: "data_bags"

verifier:
  name: inspec

client_rb:
  treat_deprecation_warnings_as_errors: true

platforms:
- name: centos-6.9
- name: centos-7.3
- name: debian-7.11
- name: debian-8.7
- name: fedora-25
- name: freebsd-11.0
- name: opensuse-leap-42.2
- name: ubuntu-14.04
- name: ubuntu-16.04
- name: amazon-2017.03

suites:
- name: resources
  run_list:
    - recipe[sysctl_test::resources]
- name: attributes
  run_list:
    - recipe[sysctl_test::attributes]
- name: attributes-empty
  run_list:
    - recipe[sysctl_test::attributes_empty]
